### PR TITLE
gracefully shutdown test context

### LINKED ISSUE #1122: Test-Context Error handling is not graceful
**Citrus Version**

`main@0c48227`

**Expected behavior**

`TestContext#handleError(String, String, String, Exception)` returns the original exception, no matter what.

Link: https://github.com/citrusframework/citrus/blob/main/core/citrus-api/src/main/java/org/citrusframework/context/TestContext.java#L435.

**Actual behavior**

Whenever one of the listeners fails, this exception will be thrown instead of the original one. This `testListeners...` 3-tuple must be "graceful", catch any exceptions that would occur during invocation and handle it. Finally return the original `cause`.

### PR DESCRIPTION
**Pull request by bbortt**
closes #1122.

### CODE REVIEW

File: core/citrus-api/src/test/java/org/citrusframework/context/TestContextUnitTest.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+        doThrow(cause).when(testListenerMock).onTestFinish(any(TestContext.EmptyTestCase.class));
+
+        invokeHandleErrorOnFixture(cause);
+
+        verify(testListenerMock).onTestStart(any(TestContext.EmptyTestCase.class));
+        verify(testListenerMock).onTestFailure(any(TestContext.EmptyTestCase.class), any(CitrusRuntimeException.class));
+        verify(testListenerMock).onTestFinish(any(TestContext.EmptyTestCase.class));
+    }
+
+    private TestListener fixtureWithTestListeners() {
```
Comment (tschlat) [inline core/citrus-api/src/test/java/org/citrusframework/context/TestContextUnitTest.java:66]: Just to add something to this review:
the name of this method implies, that it returns the fixture wired with listeners. Instead it does exactly this, but returns the listeners.

So maybe use: attachTestListenerMockToFixture
