### PR TITLE
fix(#922): Citrus 4.0 refactoring

### LINKED ISSUE #871: jetty server v11 with next citrus breaking release
see https://github.com/citrusframework/citrus/pull/869.

### LINKED ISSUE #907: spring 6.0.0 compatibility
tracking issue, so "the world" knows that I am working on making citrus (and -simulator later on) sprint 6.0.0 compatible.

branch: https://github.com/citrusframework/citrus/blob/feature/spring-600-upgrade/pom.xml#L204.

### PR DESCRIPTION
**Pull request by christophd**
- Use Citrus 4.0.0-SNAPSHOT
- Use Java 17 as minimum requirement
- Update to Spring 6.0.6 (see #907)
- Update to Spring WS 4.0.2
- Update to Spring Integration 6.0.3
- Update to Spring Restdocs 3.0.0
- Update Jetty 11.0.14 (see #871)
- Update to HttpClient 5.2.1
- Update to Apache Camel 4.0.0-M2
- Use Active MQ Artemis 2.28.0
- Use GreenMail 2.0.0 instead of SubethaSmtp
- Switch to Jakarta dependencies (instead of javax.*)
- Jakarta JMS API 3.1.0
- Jakarta Validation 3.0.2
- Jakarta Websocket API 2.1.0
- Jakarta Servlet API 6.0.0
- Saaj 3.0.0
- JaxB 4.0.2
- Kafka 3.4.0
- SLF4J 2.0.6
- Mockito 5.2.0
- Snakeyaml 2.0

Noteworthy:
- Keep using HttpClient 4.x for citrus-remote modules
- Keep using Jetty 9.x for citrus-jdbc module
- Move to ActiveMQ Artemis as it supports Jakarta libs
- Move from SubethaSMTP to GreenMail as it supports Jakarta libs
- Successor PR of #904

Closes #904
Fixes #907
Fixes #871

### CODE REVIEW

**Comment by christophd** [comment]
With this PR the main branch becomes new Citrus 4.0.0
Use 3.x branch for maintenance of Citrus 3

File: core/citrus-base/src/main/java/com/consol/citrus/util/SocketUtils.java [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+
+    /**
+     * Check if the specified TCP port is currently available on localhost.
+     */
+    private static boolean isPortAvailable(int port) {
+        try {
+            ServerSocket serverSocket = ServerSocketFactory.getDefault()
+                    .createServerSocket(port, 1, InetAddress.getByName("localhost"));
+            serverSocket.close();
```
Comment (bbortt) [inline core/citrus-base/src/main/java/com/consol/citrus/util/SocketUtils.java:76]: well, there is a reason spring removed it's implementation of this.. it's potentially unsafe and a source for flaky tests. why wouldn't you rely on the underlying systems to choose their port? I think it worked on the predecessor branch.. or didn't it?

File: endpoints/citrus-http/src/test/java/com/consol/citrus/http/integration/HttpMessageControllerJavaIT.java [hunk 2]
```diff
@@ -56,7 +56,7 @@ public void httpMessageControllerIT() {
                     .get()
                     .message(new HttpMessage()
                         .method(HttpMethod.GET)
-                        .contentType("text/html")
+                        .header("contentType","text/html")
```
Comment (bbortt) [inline endpoints/citrus-http/src/test/java/com/consol/citrus/http/integration/HttpMessageControllerJavaIT.java:59]: these lines are not properly formatted:

```suggestion
                        .header("contentType", "text/html")
```

File: endpoints/citrus-http/src/test/java/com/consol/citrus/http/yaml/HttpClientTest.java [hunk 3]
```diff
@@ -45,6 +45,7 @@
 import com.consol.citrus.message.MessageHeaders;
 import com.consol.citrus.message.MessageQueue;
 import com.consol.citrus.spi.BindToRegistry;
+import com.consol.citrus.util.SocketUtils;
```
Comment (bbortt) [inline endpoints/citrus-http/src/test/java/com/consol/citrus/http/yaml/HttpClientTest.java:48]: as pointed out, I would probably not do this. we will immediately have "legacy code" in the codebase..

File: pom.xml [hunk 4]
```diff
@@ -133,21 +133,23 @@
...
     <maven.version>3.8.4</maven.version>
-    <maven.compiler.version>3.10.1</maven.compiler.version>
+    <maven.compiler.version>3.11.0</maven.compiler.version>
     <maven.compiler.release>${java.version}</maven.compiler.release>
     <maven.compiler.source>${java.version}</maven.compiler.source>
     <maven.compiler.target>${java.version}</maven.compiler.target>
 
-    <activemq.version>5.17.3</activemq.version>
+    <failsafe.version>2.22.2</failsafe.version>
+    <surefire.version>2.22.2</surefire.version>
```
Comment (bbortt) [inline pom.xml:145]: you're not liking the (stable!) 3M-releases here, but use it for camel? 😉 I don't really mind it, but it feels kinda strange.. anyway, failsafe and surefire 3 are out for like a week or so. we should upgrade this in a follow up PR.

**Review by bbortt — COMMENTED** [review]
I like how GitHub lags when I am reviewing this PR 😆 looks good to me, just one or two comments.

File: core/citrus-base/src/main/java/com/consol/citrus/util/SocketUtils.java (hunk 1 above)
Comment (christophd) [reply core/citrus-base/src/main/java/com/consol/citrus/util/SocketUtils.java:76]: I think the reason that Spring has removed this utility is because it has been part of their production code base. Citrus is a test framework that usually is only used in test scope. Also Citrus itself is using this utility only in unit testing and in EmbeddedKafkaServer that also is only used in unit testing scope.

Given this context I still think that this utility is a clever and nice solution for its purpose in Citrus code base. Of course we can also bring back the solution from the predecessor branch in a follow up PR. I honestly do not remember why I have not used it in this PR - probably the merging effort has been a bit confusing for me in this area.

**Review by bbortt — APPROVED** [review]

**Comment by bbortt** [comment]
great effort @christophd ! thanks so much.

I will then follow up with the renaming task next. is that ok with you?

**Comment by christophd** [comment]
@bbortt yes, please feel free to continue. many thanks!

**Comment by christophd** [comment]
@xhandalax it is hard to name a fixed release date. The plan is to release a 1st milestone 4.0.0-M1 very soon as this PR has already done a lot of 4.x work. #922 lists some of the work which is still open for 4.x
