### PR TITLE
Fix: NPE in case of response header without required attribute

### LINKED ISSUE #1170: NPE when OpenAPI declares a response header without required attribute
**Citrus Version**
4.2.1

**Expected behavior**
If a response header is declared without any `required` attribute, it should be interpreted as optional.

**Actual behavior**
There`s an exception:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "java.util.Map$Entry.getValue().required" is null
	at org.citrusframework.openapi.model.v3.Oas30ModelHelper.lambda$getRequiredHeaders$14(Oas30ModelHelper.java:222)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.citrusframework.openapi.model.v3.Oas30ModelHelper.getRequiredHeaders(Oas30ModelHelper.java:223)
	at org.citrusframework.openapi.model.OasModelHelper.delegate(OasModelHelper.java:216)
	at org.citrusframework.openapi.model.OasModelHelper.getRequiredHeaders(OasModelHelper.java:167)
	at org.citrusframework.openapi.actions.OpenApiClientResponseActionBuilder$OpenApiClientResponseMessageBuilder.build(OpenApiClientResponseActionBuilder.java:101)
	at org.citrusframework.actions.ReceiveMessageAction.createControlMessage(ReceiveMessageAction.java:276)
	at org.citrusframework.actions.ReceiveMessageAction.validateMessage(ReceiveMessageAction.java:226)
	at org.citrusframework.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:167)
	at org.citrusframework.actions.AbstractTestAction.execute(AbstractTestAction.java:59)
	at org.citrusframework.DefaultTestCase.executeAction(DefaultTestCase.java:190)
	... 8 more
```

**Test case sample**
The OpenAPI declared a Location header for a POST operation:

```openapi
      responses:
        201:
          description: Todo created
          headers:
            Location:
              description: The URL of the newly created todo.
              # required: true
              schema:
                type: string
                format: uri
```

This is used to validate the response.

### PR DESCRIPTION
**Pull request by ueberfuhr**
Resolves #1170

### CODE REVIEW

File: connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java [hunk 1]
```diff
@@ -219,7 +220,7 @@ public static Map<String, OasSchema> getRequiredHeaders(Oas30Response response)
 
         return response.headers.entrySet()
                 .stream()
-                .filter(entry -> entry.getValue().required)
+                .filter(entry -> Boolean.TRUE.equals(entry.getValue().required))
```
Comment (bbortt) [inline connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java:223]: Since this is part of a public API that can be easily accessed within the “Oas30ModelHelper”, it seems that it would be easily testable.

File: connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java [hunk 2]
```diff
@@ -42,6 +42,7 @@
 
 /**
  * @author Christoph Deppisch
+ * @author Ralf Ueberfuhr
  */
```
[the remark this answers is not in the document]
Comment (ueberfuhr) [reply connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java:46]: Okay, if this is disturbing, I'll remove the @author tag (but only my own) to minimize the diffs. Is this okay for you @bbortt ?

File: connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java (hunk 1 above)
Comment (ueberfuhr) [reply connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java:222]: @bbortt - I have created a test, please check.

Comment (bbortt) [reply connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java:222]: awesome, many thanks! that proves the desired behavior quit well 🚀

**Review by bbortt — APPROVED** [review]
